import door1 from '../assets/colors/L001.jpg';
import door2 from '../assets/colors/L002.jpg';
import door3 from '../assets/colors/L003.jpg';
import door4 from '../assets/colors/L005-L007.jpg';
import door5 from '../assets/colors/L006-L012.jpg';
import door6 from '../assets/colors/L008.jpg';
import door7 from '../assets/colors/L009.jpg';
import door8 from '../assets/colors/L010.jpg';
import door9 from '../assets/colors/L011.jpg';
import door10 from '../assets/colors/M001.jpg';
import door11 from '../assets/colors/M003-M102.jpg';
import door12 from '../assets/colors/M005-M105.jpg';
import door13 from '../assets/colors/M006-M103.jpg';
import door14 from '../assets/colors/M101.jpg';
import door15 from '../assets/colors/M102.jpg';
import door16 from '../assets/colors/M105.jpg';
import door17 from '../assets/colors/M106.jpg';
import door18 from '../assets/colors/M107-M203.jpg';
import door19 from '../assets/colors/M108.jpg';
import door20 from '../assets/colors/M201.jpg';
import door21 from '../assets/colors/M202.jpg';
import door22 from '../assets/colors/Z001.jpg';
import door23 from '../assets/colors/Z002-Z006.jpg';
import door24 from '../assets/colors/Z003.jpg';
import door25 from '../assets/colors/Z005.jpg';
import door26 from '../assets/colors/Z007.jpg';
import door27 from '../assets/colors/Z008.jpg';
import door28 from '../assets/colors/Z009.jpg';
import door29 from '../assets/colors/Z010.jpg';
import door30 from '../assets/colors/Z011.jpg';
import door31 from '../assets/colors/Z012.jpg';
import door32 from '../assets/colors/Z013.jpg';
import door33 from '../assets/colors/Z015.jpg';
import door34 from '../assets/colors/Z016.jpg';
import door35 from '../assets/colors/Z017.jpg';
import door36 from '../assets/colors/Z018.jpg';
import door37 from '../assets/colors/Z019.jpg';
import door38 from '../assets/colors/Z020.jpg';
import door39 from '../assets/colors/Z021.jpg';
import door40 from '../assets/colors/Z022.jpg';
import door41 from '../assets/colors/Z025.jpg';
import door42 from '../assets/colors/Z026.jpg';
import door43 from '../assets/colors/Z027.jpg';
import door44 from '../assets/colors/Z028.jpg';
import door45 from '../assets/colors/Z029.jpg';

export const doorStyles = [
	{
		id: 'classic1',
		name: 'Luxury Panel L001',
		category: 'Luxury',
		basePrice: 4500,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door1,
		thumbnail: door1,
		description: 'Elegant luxury door with a refined finish',
		features: ['Premium Hardware', 'Sound Insulation', 'Enhanced Security'],
	},
	{
		id: 'classic2',
		name: 'Luxury Panel L002',
		category: 'Luxury',
		basePrice: 4800,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door2,
		thumbnail: door2,
		description: 'Stylish luxury door with modern aesthetics',
		features: ['Weather Resistant', 'Thermal Insulation', 'Elegant Design'],
	},
	{
		id: 'classic3',
		name: 'Luxury Panel L003',
		category: 'Luxury',
		basePrice: 4700,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door3,
		thumbnail: door3,
		description: 'Sophisticated luxury door for contemporary homes',
		features: ['Custom Finish', 'Premium Build', 'Superior Security'],
	},
	{
		id: 'dual-tone1',
		name: 'Dual-Tone Panel L005-L007',
		category: 'Luxury',
		basePrice: 5200,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door4,
		thumbnail: door4,
		description: 'Dual-tone luxury door with premium materials',
		features: [
			'Modern Hardware',
			'Smart Lock Compatible',
			'Weather Protection',
		],
	},
	{
		id: 'exclusive1',
		name: 'Exclusive Panel L006-L012',
		category: 'Luxury',
		basePrice: 5400,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door5,
		thumbnail: door5,
		description: 'Exclusive luxury door for high-end homes',
		features: ['Premium Grade', 'Modern Style', 'Enhanced Security'],
	},
	{
		id: 'classic4',
		name: 'Classic Panel L008',
		category: 'Classic',
		basePrice: 4600,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door6,
		thumbnail: door6,
		description: 'Classic luxury door with timeless design',
		features: ['Classic Finish', 'Weather Resistant', 'Thermal Insulation'],
	},
	{
		id: 'classic5',
		name: 'Minimalist Classic Panel L009',
		category: 'Classic',
		basePrice: 4900,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door7,
		thumbnail: door7,
		description: 'Minimalistic luxury door with superior build',
		features: [
			'Premium Materials',
			'Smart Lock Compatible',
			'Thermal Protection',
		],
	},
	{
		id: 'modern1',
		name: 'Modern Flush M001',
		category: 'Modern',
		basePrice: 3200,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door10,
		thumbnail: door10,
		description: 'Modern door with minimalist aesthetics',
		features: ['Smart Features', 'Weather Resistant', 'Thermal Protection'],
	},
	{
		id: 'modern2',
		name: 'Contemporary Panel M003-M102',
		category: 'Modern',
		basePrice: 3400,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door11,
		thumbnail: door11,
		description: 'Contemporary door with premium design',
		features: ['Premium Hardware', 'Sound Protection', 'Elegant Style'],
	},
	{
		id: 'modern3',
		name: 'Modern High-Tech Panel M006-M103',
		category: 'Modern',
		basePrice: 3700,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door13,
		thumbnail: door13,
		description: 'High-tech modern door with smart features',
		features: [
			'Smart Lock Compatible',
			'Premium Materials',
			'Sound Protection',
		],
	},
	{
		id: 'modern4',
		name: 'Classic Modern Panel M101',
		category: 'Modern',
		basePrice: 3500,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door14,
		thumbnail: door14,
		description: 'Classic modern door for elegant homes',
		features: ['Weather Resistant', 'Sound Insulation', 'Premium Build'],
	},
	{
		id: 'modern5',
		name: 'Sleek Modern Panel M102',
		category: 'Modern',
		basePrice: 3300,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door15,
		thumbnail: door15,
		description: 'Sleek modern door with contemporary finishes',
		features: ['Modern Style', 'Enhanced Security', 'Thermal Protection'],
	},
	{
		id: 'modern6',
		name: 'Contemporary Modern Panel M105',
		category: 'Modern',
		basePrice: 3800,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door16,
		thumbnail: door16,
		description: 'Modern design with advanced materials',
		features: ['Smart Lock Compatible', 'Weather Resistant', 'Premium Build'],
	},
	{
		id: 'modern7',
		name: 'Advanced Security Panel M106',
		category: 'Modern',
		basePrice: 3600,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door17,
		thumbnail: door17,
		description: 'Elegant modern door with advanced security features',
		features: ['Weather Resistant', 'Sound Protection', 'Premium Finish'],
	},
	{
		id: 'modern8',
		name: 'Dual Modern Panel M107-M203',
		category: 'Modern',
		basePrice: 4800,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door18,
		thumbnail: door18,
		description: 'Dual-panel modern door for high-end homes',
		features: ['Custom Design', 'Thermal Insulation', 'Enhanced Security'],
	},
	{
		id: 'modern9',
		name: 'Smart Modern Panel M108',
		category: 'Modern',
		basePrice: 4000,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door19,
		thumbnail: door19,
		description: 'Smart modern door for contemporary living',
		features: ['Smart Features', 'Elegant Style', 'Enhanced Security'],
	},
	{
		id: 'modern10',
		name: 'High-Performance Modern Panel M201',
		category: 'Modern',
		basePrice: 4000,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door20,
		thumbnail: door20,
		description: 'High-performance modern door with sleek design',
		features: ['Premium Hardware', 'Smart Features', 'Weather Resistant'],
	},
	{
		id: 'modern11',
		name: 'Minimalist Modern Panel M202',
		category: 'Modern',
		basePrice: 3900,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door21,
		thumbnail: door21,
		description: 'Advanced modern door with a minimalist look',
		features: ['Thermal Insulation', 'Sound Protection', 'Elegant Style'],
	},
	{
		id: 'classic6',
		name: 'Timeless Classic Panel Z001',
		category: 'Classic',
		basePrice: 3200,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door22,
		thumbnail: door22,
		description: 'Timeless classic door with premium materials',
		features: ['Classic Style', 'Weather Protection', 'Sound Insulation'],
	},
	{
		id: 'classic7',
		name: 'Dual Classic Panel Z002-Z006',
		category: 'Classic',
		basePrice: 3400,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door23,
		thumbnail: door23,
		description: 'Dual-panel classic door for traditional homes',
		features: ['Custom Design', 'Enhanced Security', 'Weather Resistant'],
	},
	{
		id: 'classic8',
		name: 'Elegant Classic Panel Z003',
		category: 'Classic',
		basePrice: 3300,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door24,
		thumbnail: door24,
		description: 'Elegant classic door with modern hardware',
		features: ['Premium Finish', 'Thermal Insulation', 'Enhanced Security'],
	},
	{
		id: 'classic9',
		name: 'Vintage Classic Panel Z005',
		category: 'Classic',
		basePrice: 3100,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door25,
		thumbnail: door25,
		description: 'Classic door with a vintage look',
		features: ['Vintage Style', 'Sound Protection', 'Weather Resistant'],
	},
	{
		id: 'designer1',
		name: 'Exclusive Designer Door Z007',
		category: 'Designer',
		basePrice: 5000,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door26,
		thumbnail: door26,
		description: 'Exclusive designer door with unique finishes',
		features: ['Custom Design', 'Premium Hardware', 'Weather Resistant'],
	},
	{
		id: 'designer2',
		name: 'Contemporary Designer Door Z008',
		category: 'Designer',
		basePrice: 5200,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door27,
		thumbnail: door27,
		description: 'Contemporary designer door for modern living',
		features: ['Thermal Protection', 'Smart Lock Compatible', 'Elegant Style'],
	},
	{
		id: 'designer3',
		name: 'Bold Designer Door Z009',
		category: 'Designer',
		basePrice: 5300,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door28,
		thumbnail: door28,
		description: 'Designer door with bold, unique finishes',
		features: ['Smart Features', 'Premium Grade', 'Enhanced Security'],
	},
	{
		id: 'designer4',
		name: 'Vibrant Designer Door Z010',
		category: 'Designer',
		basePrice: 5400,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door29,
		thumbnail: door29,
		description: 'Exclusive designer door with vibrant color schemes',
		features: ['Custom Finish', 'Smart Features', 'Premium Build'],
	},
	{
		id: 'designer5',
		name: 'Modern Designer Door Z011',
		category: 'Designer',
		basePrice: 5500,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door30,
		thumbnail: door30,
		description: 'Modern designer door with clean aesthetics',
		features: [
			'Premium Materials',
			'Smart Lock Compatible',
			'Weather Resistant',
		],
	},
	{
		id: 'designer6',
		name: 'Intricate Designer Door Z012',
		category: 'Designer',
		basePrice: 5600,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door31,
		thumbnail: door31,
		description: 'Designer door with intricate details and finishes',
		features: ['Elegant Design', 'Enhanced Security', 'Premium Grade'],
	},
	{
		id: 'classic10',
		name: 'Classic-Inspired Designer Door Z013',
		category: 'Classic',
		basePrice: 5000,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door32,
		thumbnail: door32,
		description: 'Classic-inspired designer door with modern upgrades',
		features: ['Vintage Look', 'Premium Build', 'Enhanced Security'],
	},
	{
		id: 'designer7',
		name: 'Sophisticated Designer Door Z015',
		category: 'Designer',
		basePrice: 5200,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door33,
		thumbnail: door33,
		description: 'Sophisticated designer door with bold features',
		features: ['Modern Hardware', 'Smart Lock Compatible', 'Weather Resistant'],
	},
	{
		id: 'designer8',
		name: 'Minimalist Designer Door Z016',
		category: 'Designer',
		basePrice: 5100,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door34,
		thumbnail: door34,
		description: 'Unique designer door with minimalist appeal',
		features: ['Custom Design', 'Smart Features', 'Premium Build'],
	},
	{
		id: 'classic11',
		name: 'Rich Finish Designer Door Z017',
		category: 'Classic',
		basePrice: 4800,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door35,
		thumbnail: door35,
		description: 'Classic designer door with rich finishes',
		features: ['Classic Style', 'Premium Hardware', 'Enhanced Security'],
	},
	{
		id: 'designer9',
		name: 'Superior Designer Door Z018',
		category: 'Designer',
		basePrice: 5500,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door36,
		thumbnail: door36,
		description: 'Modern designer door with superior features',
		features: ['Elegant Style', 'Premium Grade', 'Smart Features'],
	},
	{
		id: 'classic12',
		name: 'Classic Designer Door Z019',
		category: 'Classic',
		basePrice: 4400,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door37,
		thumbnail: door37,
		description: 'Classic designer door with intricate features',
		features: ['Vintage Aesthetics', 'Premium Materials', 'Durable Finish'],
	},
	{
		id: 'classic13',
		name: 'Heritage Designer Door Z020',
		category: 'Classic',
		basePrice: 4300,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door38,
		thumbnail: door38,
		description: 'Heritage-style designer door for timeless homes',
		features: ['Weather Resistant', 'Classic Appeal', 'Durable Construction'],
	},
	{
		id: 'classic14',
		name: 'Elegant Classic Door Z021',
		category: 'Classic',
		basePrice: 4500,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door39,
		thumbnail: door39,
		description: 'Elegant classic door with refined features',
		features: ['Custom Finish', 'Enhanced Security', 'Premium Grade'],
	},
	{
		id: 'modern12',
		name: 'Contemporary Modern Door Z022',
		category: 'Modern',
		basePrice: 4700,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door40,
		thumbnail: door40,
		description: 'Contemporary modern door with sleek design',
		features: ['Elegant Finish', 'Smart Lock Compatible', 'Durable Materials'],
	},
	{
		id: 'elite3',
		name: 'Elite Designer Door Z025',
		category: 'Elite',
		basePrice: 6000,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door41,
		thumbnail: door41,
		description: 'Elite designer door with unique finishes',
		features: ['Custom Design', 'Premium Materials', 'Elegant Style'],
	},
	{
		id: 'elite4',
		name: 'Exclusive Elite Door Z026',
		category: 'Elite',
		basePrice: 6200,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door42,
		thumbnail: door42,
		description: 'Exclusive elite door with modern styling',
		features: ['Smart Features', 'Enhanced Security', 'Elegant Style'],
	},
	{
		id: 'elite5',
		name: 'Luxury Elite Door Z027',
		category: 'Elite',
		basePrice: 6400,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door43,
		thumbnail: door43,
		description: 'Luxury elite door with smart home integration',
		features: ['Smart Home Compatible', 'Premium Finish', 'Enhanced Security'],
	},
	{
		id: 'elite6',
		name: 'Superior Elite Door Z028',
		category: 'Elite',
		basePrice: 6500,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door44,
		thumbnail: door44,
		description: 'Elite designer door with superior craftsmanship',
		features: ['Custom Design', 'Smart Lock Compatible', 'Elegant Style'],
	},
	{
		id: 'elite7',
		name: 'Luxury Exclusive Door Z029',
		category: 'Elite',
		basePrice: 6800,
		dimensions: { width: 1, height: 2, depth: 0.05 },
		allowedHandles: ['all'],
		allowedGlass: ['top', 'full'],
		texture: door45,
		thumbnail: door45,
		description: 'Luxury elite door for exclusive spaces',
		features: ['Smart Features', 'Premium Grade', 'Enhanced Security'],
	},
];
